spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shm
    username: shm
    password: shm00
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  # create | update | validate | none (운영은 'none' 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
